site_name: TNSI_Projet_1

nav:
 - Accueil : index.md
 - Turtle:
   - main.pyw: turtle/main.md
   - fonctions:
     - formes.py: turtle/formes.md
   - objets:
     - exterieur.py: turtle/exterieur.md
 - Ascii:
   - Carr√©: ascii/carre.md
   - Triangle: ascii/triangle.md
   - Sapin: ascii/sapin.md
 - Image Ascii: image_ascii.md
   


theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - search.highlight
    - content.code.copy
    - navigation.instant
    - palette
    - palette.toggle
    - palette.scheme
    - palette.media
    - header.autohide
    - header.title
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Basculer en mode clair


markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
